food_order_project/food_order_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accountApp.views import *
from restaurantApp.views import *

urlpatterns = [
    path('', include('accountApp.urls')),
    path('', include('restaurantApp.urls')),
    path('', include('orderApp.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

food_order_project/orderApp/urls.py
from typing import ChainMap
from django.urls import path
from orderApp.views import *




urlpatterns = [
    path('update_item/',updateItem,name='update_item'),
    path('cart/',cart,name='cart'),
    path('checkout/',check,name='checkout'),
    

]

food_order_project/restaurantApp/models.py
from django.db import models


class Restaurant(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True, max_length=500)
    image = models.ImageField(blank=True, null=True, upload_to='Restaurent-images')

    def __str__(self):
        return self.name


class Category(models.Model):
    restaurant = models.ForeignKey(Restaurant, blank=True, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='Category-images/')

    def __str__(self):
        return "Restaurant Name: " + self.restaurant.name + "    " + "Category:  " + self.name

    @property
    def get_restaurant(self):
        return self.restaurant.name


class FoodItem(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_length=100, decimal_places=2, max_digits=5)
    image = models.ImageField(blank=True, null=True, upload_to='FoodItem-images')

    def __str__(self):
        return self.name + " " + "(" + self.category.restaurant.name + ")"

    @property
    def get_restaurant(self):
        return self.category.restaurant.name

    @property
    def get_category(self):
        return self.category.name


class Review(models.Model):
    restaurant = models.ForeignKey(Restaurant, models.CASCADE)
    comment = models.TextField(max_length=250)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.restaurant.name

food_order_project/templates/addressUpdate.html
{% extends 'base1.html' %}
{%load static%}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock title %}
{% block body %}


<div class="container mt-2 w-50">
    <div class="container bg-secondary border rounded">
        <h3 class="text-center p-4 text-light">Address Update</h3>
    </div>
    <div class="container border rounded m-auto">
        <form method="POST" action="">
            {% csrf_token %}
            <div class="form-group my-2">
                <label class="form-label">Address</label>
                <!-- <textarea class="form-control" rows="5" id="comment" placeholder="Address...."></textarea> -->
                {{ a_form.address|as_crispy_field }}
            </div>
            <div class="form-group my-2">
                <label class="form-label">Area</label>
                <!-- <input class="form-control" placeholder="Enter the name of your area....."> -->
                {{ a_form.area|as_crispy_field }}
            </div>
            <div class="row">
                <div class="col-md-5 my-2">
                    <div class="form-group">
                        <label class="form-label">House Number</label>
                        {{ a_form.houseNo|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-4 my-2">
                    <div class="form-group">
                        <label class="form-label">Road Number</label>
                        {{ a_form.roadNo|as_crispy_field }}
                    </div>
                </div>
                <div class="col-md-3 my-2">
                    <div class="form-group">
                        <label class="form-label">Zip Code</label>
                        {{ a_form.zipCode|as_crispy_field }}
                    </div>
                </div>
            </div>

            <div class="form-group mt-3 mb-3">
                <input type="submit" class="form-control btn-outline-secondary" placeholder="Enter the name of your area.....">
            </div>

        </form>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


{% endblock body %}

food_order_project/templates/addtocart.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block body %}
<div class="container my-5">
  <div class="row">
   <h1 class="text-center mb-5 text-uppercase">Shopping Cart</h1>
   <div class="col-sm-8">
   <div class="card">
    {% if cartObjects > 0%}
     {% for item in orderItems %}
    <div class="card-body">
     <div class="row">
      <div class="col-sm-3 text-center align-self-center"><img src="{{item.product.image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
      <div class="col-sm-9">
        <h5 class="text-uppercase">{{item.product.name}}</h5>
        <p class="mb-2 text-muted small">Description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum quas, nihil vel velit sed, quos consequatur maiores odio libero eius est in mollitia quo minus dolorum culpa consectetur, ipsam unde!</p>
        <div class="my-3">
         <label for="quantity">Quantity:</label>
         <button  class="btn update-cart" data-fooditem="{{item.product.id}}" data-action="remove"><i class="fas fa-minus-square fa-lg" ></i></button>
          <span data-quantity="{{item.quantity}}" id="quantity">{{item.quantity}}</span>
         <button  class="btn update-cart" data-fooditem="{{item.product.id}}" data-action="add"><i class="fas fa-plus-square fa-lg" ></i></button>
        </div> 
        <div class="d-flex justify-content-between">
         <button data-fooditem="{{item.product.id}}" data-action="delete" class="btn btn-sm btn-secondary mr-3 update-cart" data-toggle="modal" data-target="#exampleModal">Remove item </button>
         <p class="mb-0"><span><strong>€ {{item.get_total}}</strong></span></p>
        </div>
        <hr class="text-muted">
      </div>
     </div>
    </div>
    {% endfor %}
    {% else %}
    <h5 class="text-center">Cart is empty</h5>
    {% endif %}
    </div>
   </div>
 
   <div class="col-sm-4">
    <div class="card">
     <div class="card-body">
       <h3 class="m-1 p-2 text-center bg-secondary text-light rounded text-uppercase">Cart Total</h3>
       <ul class="list-group pt-4 pb-4 pl-1 pr-1">
        {% if order.get_cart_total %}
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Total Amount<span>€ {{order.get_cart_total}}</span></li>
        {% else %}
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Total Amount<span>€ 0.00</span></li>
        {% endif %}

        {% if order.shipping_charge %}
        <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping Charge<span>€ {{order.shipping_charge}}</span></li>
        {% else %}
        <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping Charge<span>€ 0.00</span></li>
        {% endif %}
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
         <div>
            <strong>Total</strong> <small>(including VAT)</small>
          </div>
          {% if order.get_cart_total %}
          <span><strong>€ {{grand_total}}</strong></span>
          {% else %}
          <span><strong>€ 0.00</strong></span>
          {% endif %}
        </li>
       </ul>
       <div class="d-grid mt-4 mb-4"><a href="{% url 'checkout' %}" class="btn btn-outline-secondary">Checkouts</a></div>
     </div>
    </div>
   </div>
   
  </div>
 </div>
{% endblock body %}



{% block JS %}

<script type="text/javascript" src="{% static 'js/cart.js' %}" async></script>

{% endblock JS %}

food_order_project/templates/all-restaurants.html
{% extends 'base1.html' %}
{%load static%}
{% load crispy_forms_tags %}
{% block title %}all-restaurants{% endblock title %}
{% block body %}

all restaurant page

{% for rest in restaurants %}
{{rest.name}}
<br>
{% endfor %}


{% for cat in cat %}
{{cat.name}}
<br>
{% endfor %}
{% endblock body %}

food_order_project/templates/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" href="#" />

    <!-- Bootstrap CSS -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />

    <!--FontAwesome CSS-->
    <!-- <link rel="stylesheet" href="{% static 'css/all.min.css' %}" /> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->


    <script type="text/javascript">
    
      var user = "{{request.user}}";



      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== "") {
          const cookies = document.cookie.split(";");
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      const csrftoken = getToken("csrftoken");
    </script>

        

    <!-- <script src="{% static 'js/cart.js' %}" async></script> -->


    <title>Food Ordering App | {% block title %} {% endblock title %}</title>
  </head>
  <body>

    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">FOOD ORDERING APP</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          </ul>
          <form class="d-flex" action="/item-search" method="get">
            {% csrf_token %}
            <input
              class="form-control me-1"
              type="search"
              placeholder="Search Food Items here..."
              aria-label="Search"
              name="query"
              id="query"
            />
            <button class="btn btn-outline-danger" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </form>
          <div>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="adc nav-item dropdown mx-2 active">
                <a
                  class="nav-link dropdown-toggle text-white"
                  href="#"
                  id="profileDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="fas fa-user"></i> {{request.user.username}}
                </a>
                <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'userProfile' %}"
                      ><i class="fas fa-user"></i> Profile</a
                    >
                  </li>
                  <!-- <li>
                    <a class="dropdown-item" href="#"
                      ><i class="fa fa-shopping-cart" aria-hidden="true"></i>
                      Orders</a
                    >
                  </li> -->
                  <li>
                    <a class="dropdown-item" href="{% url 'change_password' %}"
                      ><i class="fas fa-key"></i> Change Password</a
                    >
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'logout' %}"
                      ><i class="fas fa-sign-out-alt"></i> Logout</a
                    >
                  </li>
                </ul>
              </li>

              {% else %}
              <li class="nav-item mx-2">
                <a href="{% url 'login' %}" class="nav-link text-white"
                  >Login</a
                >
              </li>
              <li class="nav-item mx-2">
                <a href="{% url 'register' %}" class="nav-link text-white"
                  >Registration</a
                >
              </li>
              {% endif %}
              <li class="nav-item mx-2">
                <a href="{% url 'cart' %}" class="nav-link text-white">
                  {% if cartObjects %}
                  <span class="badge bg-danger" id="cart-total">{{cartObjects}}</span>
                  {% else %}
                  <span class="badge bg-danger" id="cart-total">0</span>
                  {% endif %}
                  <i class="fas fa-shopping-cart"></i
                ></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    


    {% block banner_slider %} {% endblock banner_slider %} {% block livesale %}
    {% endblock livesale %} {% block body %} {% endblock body %}

  </div>
    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
      <small class="text-white"
        >Copyright &copy; 2024 || Food Ordering Application ||
      </small>
      <img
        src="{% static 'images/payment.png' %}"
        alt=""
        srcset=""
        class="img-fluid"
        height="2px"
      />
    </footer>
    <!-- End Footer -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/myscript.js' %}" async></script>
    <!-- <script type="text/javascript" src="{% static 'js/formValidation.js' %}" async></script> -->
    <script type="text/javascript" src="{% static 'js/additional-methods.min.js' %}"></script>

    <!-- for login -->
    <script type="text/javascript" src="{% static 'js/jqueryValidation.js' %}"></script>  
    <!-- for register -->
    <script type="text/javascript" src="{% static 'js/jquery.register.js' %}"></script>
    <!-- for change password -->
    <script type="text/javascript" src="{% static 'js/jquery.change_password.js' %}"></script>
    <!-- for checkout -->
    <script type="text/javascript" src="{% static 'js/jquery.checkout.js' %}"></script>
    <!-- CDN for sweet alert -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
    {% for msg in messages %}
      {% if msg.tags == 'success' %}
        <script>
          Swal.fire({
            icon: 'success',
            title: 'Congratulations!!',
            text: '{{msg}}',
          })
        </script>
      {% else %}
        <script>
          Swal.fire({
            icon: 'error',
            title: 'Opps!!',
            text: '{{msg}}',
          })
        </script>
      {% endif %}

    {% endfor %}



    {% block JS %}

    
    
    
    {% endblock JS %}
  </body>
</html>

food_order_project/templates/changepassword.html
{% extends 'base1.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Buy Now{% endblock title %}
{% block body %}
<div class="container my-3">
 <div class="row w-50 m-auto">
 <h3 class="text-center mb-4 mt-4">Change Password</h3>
  <div class="col-sm-8 offset-sm-1 m-auto">
   <form method="POST" action="" id="changePasswordForm" class="shadow p-5 needs-validation" name="changePasswordForm" novalidate>
    {% csrf_token %}
     <div class="mb-3 from-group has-validation" id="old_password">
       <label for="old_password" class="form-label">Old Password</label>
       {{ form.old_password|as_crispy_field }}
       <small id="emailHelp" class="form-text text-danger"></small>
     </div>
     <div class="mb-3 form-group has-validation" id="new_password1">
       <label for="new_password1" class="form-label">New Password</label>
       {{ form.new_password1|as_crispy_field }}
       <small id="emailHelp" class="form-text text-danger"></small>
     </div>
     <div class="mb-3 form-group has-validation" id="new_password2">
       <label for="exampleInputPassword1" class="form-label">Confirm New Password</label>
       {{ form.new_password2|as_crispy_field }}
       <small id="emailHelp" class="form-text text-danger"></small>
     </div>
     <button type="submit" class="btn btn-outline-secondary mb-5 mt-2 container-fluid">Submit</button>
   </form>
  </div>
 </div>
</div>
{% endblock body %}

food_order_project/templates/checkout.html
{% extends 'base1.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
 <div class="row mt-5">
  <div class="col-md-6">
    <h5>Shipping Address</h5>
    <hr>
      <div class="card p-0">
        <div class="card-body">
          {% if cartObjects > 0%}
          <form action="" method="post" id="shipping-form" name="Shipping-form" novalidate onsubmit="return ShippingAddress()">
            {% csrf_token %}
            <div class="mb-3" id="add_address">
              <label for="address" class="form-label">Address*</label>
              <input type="text" class="form-control" id="address" name="address" placeholder="Enter the address..." required>
              <small id="emailHelp" class="form-text text-danger"></small>
              <div class="invalid-feedback">
                 <small id="emailHelp" class="form-text text-danger"></small>
               </div>
             </div>

             <div class="mb-3" id="add_area">
              <label for="area" class="form-label">Area*</label>
              <input type="text" class="form-control" id="area" name="area" placeholder="Enter the area..." required>
              <small id="emailHelp" class="form-text text-danger"></small>
              <div class="invalid-feedback">
                 <small id="emailHelp" class="form-text text-danger"></small>
               </div>
             </div>

             <div class="row">
               <div class="col-md-7">
                <div class="mb-3" id="add_houseNo">
                  <label for="houseNo" class="form-label">House No*</label>
                  <input type="text" class="form-control" id="houseNo" name="houseNo" placeholder="houseNo..." required>
                  <small id="emailHelp" class="form-text text-danger"></small>
                  <div class="invalid-feedback">
                     <small id="emailHelp" class="form-text text-danger"></small>
                   </div>
                 </div>
               </div>
               <div class="col-md-5">
                <div class="mb-3" id="add_zipcode">
                  <label for="zipcode" class="form-label">Zip Code*</label>
                  <input type="number" class="form-control" id="zipcode" name="zipcode" placeholder="Zip Code...." required>
                  <small id="emailHelp" class="form-text text-danger"></small>
                  <div class="invalid-feedback">
                     <small id="emailHelp" class="form-text text-danger"></small>
                   </div>
                 </div>

               </div>
             </div>
             <div class="form-group">
              <input type="submit" class="form-control btn-outline-secondary">
              </div>
          </form>
          {% else %}
          <h5 class="text-center">No Item in the cart</h5>
          {% endif %}
        </div>
      </div>
  </div>

  <div class="col-md-1">
  </div>

  <div class="col-sm-4 mt-5">
    <div class="card">
     <div class="card-body">
       <h3 class="text-center border rounded p-2 m-0">Order Summary</h3>
       <ul class="list-group pt-4 pb-4 pl-1 pr-1">
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0 ">
          <span id="image" class="ml-2">Image</span>
          <span id="name" class="">Name</span>
          <span id="qty" class="">Qty</span>
        </li>
         {% for item in orderItems %}
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
          <img class="m-2" src="{{item.product.image.url}}" alt="" height="50px" width="50px">
          <span>{{item.product.name}}</span>
          <span>x{{item.quantity}}</span>
          
        </li>
        {% endfor %}
        <hr>
        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-2">
         <div>
            <strong>Total</strong> <small>(including VAT)</small>
          </div>
          {% if grand_total %}
          <span><strong>€ {{grand_total}}</strong></span>
          {% else %}
          <span><strong>€ 0.00</strong></span>
          {% endif %}
  
        </li>
       </ul>
     </div>
    </div>
   </div>
  </div>
  <div class="row p-4 m-5">

  </div>
</div>
{% endblock body %}

{% block JS%}
<script>


</script>

{% endblock JS %}

food_order_project/templates/customerregistration.html
{% extends 'base1.html' %} {% load static %} {% block title %}Customer
{%load static%}
{% load crispy_forms_tags %}
Registration{% endblock title %} {% block body %}
<div class="container">
  <div class="row my-3">
    <div class="col-sm-6 offset-sm-3">
      <h3 class="text-center">Registration Here</h3>
      <hr />

      <form action="" method="post" class="shadow p-5 needs-validation" id="form" name="registerForm" novalidate>
         {% csrf_token %}
        <div class="mb-3 form-group" id="reg_username">
          <label for="reg_username" class="form-label">Username</label>
          {{ form.username|as_crispy_field }}
          <small id="emailHelp" class="form-text text-danger"></small>
        </div>
        <div class="mb-3 form-group" id="reg_email">
          <label for="reg_email" class="form-label">Email</label>
          {{ form.email|as_crispy_field }}
          <small id="emailHelp" class="form-text text-danger"></small>
        </div>
        <div class="mb-3 form-group" id="reg_password1">
          <label for="reg_password1" class="form-label">Password</label>
          {{ form.password1|as_crispy_field }}
          <small id="emailHelp" class="form-text text-danger"></small>

        </div>
        <div class="mb-3 form-group" id="reg_password2">
          <label for="reg_password2" class="form-label"
            >Confirm Password</label
          >
          {{ form.password2|as_crispy_field }}
          <small id="emailHelp" class="form-text text-danger"></small>
        </div>
        <div class="text-end">
          <button type="submit" class="btn btn-outline-secondary container-fluid">Submit</button>
        </div>
        <br />
        <div class="text-center text-primary fw-bold">
          <small
            >Already Have Account ?
            <a href="{% url 'login' %}" class="text-danger">Login Now</a>
          </small>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock body %}

food_order_project/templates/footer.html
{% load static %}
<!-- footer section  -->

<section class="footer">

    <div class="share">
        <a href="#" class="btn">facebook</a>
        <a href="#" class="btn">twitter</a>
        <a href="#" class="btn">instagram</a>
        <a href="#" class="btn">pinterest</a>
        <a href="#" class="btn">linkedin</a>
    </div>

    <h1 class="credit"> created by <span> mr. web designer </span> | all rights reserved! </h1>

</section>

<!-- scroll top button  -->
<a href="#home" class="fas fa-angle-up" id="scroll-top"></a>

<!-- loader  -->
<div class="loader-container">
    <img src="images/loader.gif" alt="">
</div>

food_order_project/templates/restaurant-menu.html
{% extends 'base1.html' %}
{%load static%}
{% load crispy_forms_tags %}
{% block title %}all-restaurants{% endblock title %}
{% block body %}

<div class="container">
  <div class="jumbotron mt-3">
    <img class="d-block w-100" src="{% static 'images/banner/restaurant.jpg' %}" alt="...">
    <h1 class="display-6 text-center">{{restaurant.name}}- {{restaurant.address}}</h1>
    <p class="lead text-center">Restaurant Rating : {{ result}}</p>
    <!-- <hr class="my-4"> -->
  </div>
  <div class="container">
    {% for cat in category %}
    
    <div class="container mt-4">
      <hr>
      <h3 class="bg-secondary text-center text-light mx-auto p-2">{{cat.name}}</h3>
      <div class="row">
        {% for fooditem in cat.fooditem_set.all %}
        <div class="col-md-4 mt-2">
          <div class="card " style="width: 18rem;">
            <img class="card-img-top" src="{{fooditem.image.url}}">
            <div class="card-body text-center">
              <h5 class="card-title">{{fooditem.name}}</h5>
              <span class="text-danger"><br></span>
              <span class="text-danger font-weight-bold">€ {{fooditem.price}}<br></span>
              <div>
                <button data-fooditem="{{fooditem.id}}" data-action="add" class="btn btn-outline-secondary mt-2 add-btn update-cart" id="{{fooditem.id}}">Add to cart</button>
              </div>
              
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="container mt-2">
    <h3>Reviews: </h3>
    {% for com in comment %}
    <h6 class="text-bold">{{com.comment}}</h6>
    <span>{{com.created_at}}</span><br>
    <hr>
    {% endfor %}
  </div>
</div>


{% endblock body %}


{% block JS %}
<!-- <script type="text/javascript" src="{% static 'js/localStorage.js' %}" async></script> -->
<script type="text/javascript" src="{% static 'js/cart.js' %}" async></script>
{% endblock JS%}